<?php
$products = $this->getProduct();
?>

<div id="order-search" class="order-search-items">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <div style="float: right;"><button id="id_872ce6c59836931456b42d657ef6e718" title="Add Selected Product(s) to Order" type="button" class="scalable add" onclick="productGridAddSelected()"><span><span><span>Add Selected Product(s) to Order</span></span></span></button></div>
            <h4 class="fieldset-legend head-catalog-product icon-head">Please Select Products to Add</h4>
        </div>
        <div class="fieldset">
            <div id="sales_order_create_search_grid">
                <table cellspacing="0" class="actions">
                    <tbody>
                        <tr>
                            <td class="pager">
                                Page
                                <img src="http://127.0.0.1/magento/skin/adminhtml/default/default/images/pager_arrow_left_off.gif" alt="Go to Previous page" class="arrow"><input type="text" name="page" value="1" class="input-text page" onkeypress="sales_order_create_search_gridJsObject.inputPage(event, '1')"><img src="http://127.0.0.1/magento/skin/adminhtml/default/default/images/pager_arrow_right_off.gif" alt="Go to Next page" class="arrow">

                                of 1 pages <span class="separator">|</span>
                                View <select name="limit" onchange="sales_order_create_search_gridJsObject.loadByElement(this)">
                                    <option value="20" selected="selected">20</option>
                                    <option value="30">30</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                    <option value="200">200</option>
                                </select>
                                per page<span class="separator">|</span>
                                Total 2 records found <span id="sales_order_create_search_grid-total-count" class="no-display">2</span>
                            </td>
                            <td class="filter-actions a-right"><button id="id_3d909c9e7a4f07e10f9a5ac8bfda0535" title="Reset Filter" type="button" class="scalable " onclick="sales_order_create_search_gridJsObject.resetFilter()"><span><span><span>Reset Filter</span></span></span></button><button id="id_2166311b3f8c8336e54089882d89978c" title="Search" type="button" class="scalable task" onclick="sales_order_create_search_gridJsObject.doFilter()"><span><span><span>Search</span></span></span></button></td>
                        </tr>
                    </tbody>
                </table>
                <div class="grid">
                    <div class="hor-scroll">
                        <table cellspacing="0" class="data" id="sales_order_create_search_grid_table">
                            <colgroup>
                                <col width="60">
                                <col>
                                <col width="80">
                                <col width="100">
                                <col width="55">
                                <col width="1">
                            </colgroup>
                            <thead>
                                <tr class="headings">
                                    <th><span class="nobr"><a href="#" name="entity_id" title="asc" class="sort-arrow-desc"><span class="sort-title">ID</span></a></span></th>
                                    <th><span class="nobr"><a href="#" name="name" title="asc" class="not-sort"><span class="sort-title">Product Name</span></a></span></th>
                                    <th><span class="nobr"><a href="#" name="sku" title="asc" class="not-sort"><span class="sort-title">SKU</span></a></span></th>
                                    <th><span class="nobr"><a href="#" name="price" title="asc" class="not-sort"><span class="sort-title">Price</span></a></span></th>
                                    <th class="a-center no-link"><span class="nobr">Select</span></th>
                                    <th class=" no-link last"><span class="nobr">Qty To Add</span></th>
                                </tr>
                                <tr class="filter">
                                    <th>
                                        <div class="field-100"><input type="text" name="entity_id" id="sales_order_create_search_grid_filter_entity_id" value="" class="input-text no-changes"></div>
                                    </th>
                                    <th>
                                        <div class="field-100"><input type="text" name="name" id="sales_order_create_search_grid_filter_name" value="" class="input-text no-changes"></div>
                                    </th>
                                    <th>
                                        <div class="field-100"><input type="text" name="sku" id="sales_order_create_search_grid_filter_sku" value="" class="input-text no-changes"></div>
                                    </th>
                                    <th>
                                        <div class="range">
                                            <div class="range-line"><span class="label">From:</span><input type="text" name="price[from]" id="sales_order_create_search_grid_filter_price_from" value="" class="input-text no-changes"></div>
                                            <div class="range-line"><span class="label">To : </span><input type="text" name="price[to]" id="sales_order_create_search_grid_filter_price_to" value="" class="input-text no-changes"></div>
                                        </div>
                                    </th>
                                    <th class="a-center no-link"><span class="head-massaction"><select name="in_products" id="sales_order_create_search_grid_filter_in_products" class="no-changes">
                                                <option value="">Any</option>
                                                <option value="1">Yes</option>
                                                <option value="0">No</option>
                                            </select></span></th>
                                    <th class=" no-link last">&nbsp;</th>
                                </tr>
                            </thead>
                            <?php foreach ($products as $product) : ?>
                                <tbody>
                                    <tr title="#" class="even pointer">
                                        <td class=" ">
                                            <?php echo $product->getId() ?>
                                        </td>
                                        <td class=" "><a href="javascript:void(0)" style="color: #CCC;" class="f-right" disabled="disabled">Configure</a>
                                            <?php echo $product->getName() ?></td>
                                        <td class=" ">
                                            <?php echo $product->getSku() ?></td>
                                        <td class="a-center price a-right ">
                                            <?php echo $product->getPrice() ?> </td>
                                        <td class="a-center "><input type="checkbox" value="<?php echo $product->getId(); ?>" name="product[<?php echo $product->getId(); ?>]" class="checkbox"></td>
                                        <td class="a-center last"><input type="text" name="qty" value="" class="input-text qty" enabled=""></td>
                                    </tr>
                                </tbody>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script type="text/javascript">
    function productGridAddSelected() {
        var form = document.getElementById('edit_form');
        form.setAttribute('action', "<?php echo $this->getUrl('*/*/save'); ?>");
        form.submit();
    }
</script>