<?php $methods = $this->getShippingMethod();
$cart = $this->getCart();
?>

<div id="order-shipping_method" class="box-right">
    <div>
        <div class="entry-edit" style="position: relative;">
            <div class="entry-edit-head">
                <div style="float: right;"></div>
                <h4 class="fieldset-legend head-shipping-method icon-head">Shipping Method</h4>
                <button type="button" onclick="shipping()" style="float: right;">Save Shipping</button>
            </div>
            <div class="fieldset">
                <div id="order-shipping-method-choose">
                    <dl class="shipment-methods">
                        <?php foreach ($methods as $code => $method) : ?>
                            <?php if ($method->getConfigData('price')) : ?>
                                <dt><strong><?php echo $method->getConfigData('title') ?></strong></dt>
                                <dd>
                                    <ul>
                                        <li>
                                            <input type="radio" name="method[shipping]" value="<?php echo $code ?>,<?php echo $method->getConfigData('price') ?>" <?php if ($cart->getShippingMethod() == $code) : ?>checked<?php endif; ?>>
                                            <label for="<?php echo $code ?>"><strong>₹<?php echo $method->getConfigData('price') ?></strong></label>
                                        </li>
                                    </ul>
                                </dd>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>
</div>